name: Trigger Installer Update & Code Assets
on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]
jobs:
  trigger-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Installer Update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: LILCMU/gogo7-firmware-installer
          event-type: firmware-release
  trigger-code-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Code Assets
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: LILCMU/gogo-code-assets
          event-type: fetch-gogo7-firmware
